---
version: 1.2
workflows:
  - name: hic-pipeline
    publish: true
    subclass: WDL
    primaryDescriptorPath: /hic.wdl
    testParameterFiles:
      - /dockstore_test_input.json
    authors:
      - name: Paul Sud
        orcid: https://orcid.org/0000-0003-1667-4694
