__title__ = "hic-pipeline"
__version__ = "1.1.1"
__description__ = "ENCODE Hi-C uniform processing pipeline."
__url__ = "https://github.com/ENCODE-DCC/hic-pipeline"
__uri__ = __url__
__author__ = "Paul Sud"
__email__ = "encode-help@lists.stanford.edu"
__license__ = "MIT"
__copyright__ = "Copyright (c) 2020 ENCODE DCC"
